# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Build with dotnet
        run: dotnet build pigofpigs-api.sln -c Release

      - name: dotnet publish
        run: dotnet publish pigofpigs-api.sln -c Release -o ${{env.DOTNET_ROOT}}/publish

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: "pigofpigs-api"
          slot-name: "production"
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_7e7082d06aa6497b8c645dd444a7707c }}
          package: ${{env.DOTNET_ROOT}}/publish
